#server port
server:
  port: 7002

#eureka服务配置
eureka:
  instance:
    hostname: eureka-server7002.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka